CREATE TABLE IF NOT EXISTS 'servers' (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  serverName TEXT NOT NULL UNIQUE, 
  serverAddress TEXT NOT NULL UNIQUE,
  rconPassword TEXT NOT NULL,
  targetGame TEXT NOT NULL,
  createdBy TEXT NOT NULL,
  createdAt DATETIME NOT NULL,
  modifiedBy TEXT DEFAULT NULL,
  modifiedAt DATETIME DEFAULT NULL
);
